<section class="container definition">
    <h2 id="definition"><span>Définition</span></h2>

    <p><span>Le coaching scolaire vise à accompagner le jeune dans la définition et la réalisation d’un objectif scolaire ou personnel.</span></p>

    <p>Il va aborder la situation de manière globale (relations, comportements, questions de méthodes, motivation, confiance en soi, stress, difficultés d’organisation, de gestion du temps,…) afin d’amener le jeune à s’auto-évaluer, à comprendre la pertinence de ses actes, pour le mener vers l’autonomie et la responsabilisation.</p>

    <p><span>Le coach :</span></p>
    <p>·        cherche les « comment »,</p>
    <p>·        amène aux ressources, développe la réflexivité</p>
    <p>·        encourage, accompagne,</p>
    <p>·        définit des objectifs</p>
    <p>·        amène le jeune à dépasser des obstacles auxquels il est confronté.</p>

    <h3 class="title_h3 orange">Comment ?</h3>

    <p>En travaillant sur les points forts,  en cherchant des solutions concrètes, réalisables et acceptables,  en l’aidant à comprendre la pertinence de ses actes,
    </p>

    <h3 class="title_h3 orange">Pour quoi ?</h3>

    <p>Pour apprendre à se connaitre, à connaitre son profil pédagogique afin de trouver la méthode d’apprentissage qui lui correspond le mieux.</p>

    <h3 class="title_h3 orange">Pour qui ?</h3>

    <p>Les jeunes de 10 à 25 ans.</p>
</section>






