<section class="container gestion_mentale">
    <h2 id="mental_title"><span>La gestion mentale</span></h2>

    <p>Elaborée par Antoine de La Garanderie, la Gestion Mentale explore, décrit et étudie les processus mentaux dans leur diversité. Elle permet aux apprenants en difficulté de <span>découvrir leurs stratégies mentales d’apprentissage</span>, les rendre <span>conscients de leur potentiel</span> et confiants dans leurs capacités à les utiliser.</p>

    <p>Par <span>l’évocation</span>, la Gestion Mentale va permettre à l’apprenant de <span>repérer ses itinéraires mentaux</span> lors de l’accomplissement d’une tâche, d’observer ses propres stratégies pour ainsi <span>enrichir ses propres procédures mentales</span>.</p>

    <p>L’explicitation du contenu de ces évocations se fait à l’aide du dialogue pédagogique qui a pour objectif d’aboutir à la connaissance de soi, à prendre conscience des habitudes mentales utilisées lors de différentes activités, à permettre à l’apprenant de <span>se mettre en projet</span>.</p>
    <img src="www/img/gestion_mentale.jpg" alt="Gestion Mentale" class="imageinfo">
</section>