<section class="container temps">
    <h2 id="temps"><span>Gestion du temps</span></h2>

    <p>Gérer son temps = <span>s’aménager le plus de plaisir possible</span> tout en s’accordant assez de temps pour réussir ses études.</p>

    <p>Le temp de travail = les heures nécessaires pour réussir ses études et atteindre le niveau nécessaire dans une matière ou une profession.</p>

    <p>A travers certains tests comme le MBTI, nous tenterons de découvrir le profil d’apprentissage du jeune afin de déterminer ensemble les outils de gestion du temps qui lui conviennent le mieux (planning, kan-ban,…).</p>

</section>