<section class="container" id="content">

    <section id="Julie">
        <h2><span>Julie Petit</span></h2>
        <img src="www/img/Julie-photo-BnW.png"  titre="photo de Julie Petit">
        <p>Logopède et coach scolaire de formation</p>
    </section>

    <section id="presentation">
        <p><span>Diplômée en logopédie</span>, je prends en charge depuis quelques années des jeunes enfants, enfants et adolescents présentant des difficultés touchant les différentes facettes du langage (langage oral, langage écrit, et mathématique).</p>
        <p><span>Formée notamment en mind mapping, gestion mentale, gestion mentale et motivation ainsi qu’en méthodologie de travail</span>, mon envie d’en savoir toujours plus et mon attrait grandissant pour le public adolescent m’ont poussé à entamer la formation « Coaching scolaire et des jeunes » de Gaëtan Gabriel.</p>
        <p><span>Forte de cette formation et de mon expérience antérieure en tant que logopède</span>, c’est avec plaisir que je vous accueillerai pour une demande en coaching ou en logopédie.</p>
    </section>

    <section id="actions">
        <h2 class="title actions"><span>Les différents points à aborder et développer</span></h2>

        <div class="flex" id="columns">
            <a href="index.php?page=methodologie" titre ="Méthodologie de travail"><i class="fa fa-pencil"></i> Méthodologie </a>
            <a href="index.php?page=motivation" titre ="Motivation"><i class="fa fa-child"></i>Motivation</a>
            <a href="index.php?page=organisation" titre ="Organisation"><i class="fa fa-pencil"></i> Organisation </a>
            <a href="index.php?page=gestion_temps" titre="Gestion du temps"><i class="fa fa-clock-o"></i> Gestion du temps</a>
            <a href="index.php?page=mind_mapping" titre="Mind mapping"><i class="fa fa-map"></i>Mind mapping</a>
            <a href="index.php?page=gestion_mentale" titre="Gestion mentale"><i class="fa fa-street-view"></i>Gestion mentale</a>
        </div>
    </section>

</section>