<section class="container methodologie">
    <h2 id="methodologie"><span>Méthodologie</span></h2>

    <p>Le mot méthode vient du grec « hodos » qui signifie <span>chemin à suivre</span>, ou démarches, stratégies à suivre <span>pour parvenir à un but</span>, un résultat.</p>

    <p>Plusieurs chemins peuvent conduire vers le but que l’on s’est fixé. Certains seront plus efficaces que d’autres. Il est important que le chemin choisi soit <span>personnel</span> et te convienne, car tu seras seul et <span>seul responsable de ta réussite</span>. Ce chemin sera sinueux, parsemé d’obstacles à franchir, mais s’il te convient, il te conduira là où tu veux aller. A l’aide de <span>petits objectifs que tu te fixeras</span>, tu pourras avancer pas à pas. Ces objectifs t’aideront et te motiveront pour suivre et trouver le meilleur chemin, la bonne méthode pour y arriver. <span>Ce sont les étapes, les moyens, les stratégies que tu chercheras et que tu suiveras qui constitueront ta méthode</span>.</p>

    <p>Sur ton chemin, des supporters (tes parents, tes professeur, le coach,…) t’encourageront, te conseilleront, te féliciteront pour chaque obstacle franchi, pour chaque pas effectué, pour chaque petit objectif atteint. La méthodologie constitue l’un de ces supporters.</p>

    <p>A l’arrivée, tu pourras être fier du chemin que toi seul aura parcouru ! Mais pour arriver à cette destination, il sera indispensable que tu <span>agisses</span> et que tu <span>t’impliques</span> (te donner à fond, participer).</p>

    <p>Tu es seul maitre à bord, seul à décider de l’issue du voyage !</p>
</section>