<section class="container mind_mapping">
    <h2 id="mapping_title"><span>Le Mind Mapping ou Schéma Heuristique</span></h2>

    <p><span>Mind</span> = esprit (cerveau qui réfléchit)</p>

    <p><span>Mapping</span> = carte</p>

    <p><span>Mind mapping</span> = cartographie du cerveau qui réfléchit</p>

    <p>La mind map est un outil qui va permettre de cartographier des réseaux d’idées difficiles à illustrer, et traduire la relation qui existe entre des concepts abstraits.  C’est la représentation visuelle qui le rend simple, efficace et accessible, car il est adapté au fonctionnement du cerveau qui fonctionne de manière heuristique (par découvertes successives et par associations d’idées).</p>

    <p>Le mind mapping sert à :</p>


        <p> -  rechercher des idées nouvelles </p>
        <p> -  structurer les idées </p>
        <p> -  organiser des informations </p>
        <p> -  mémoriser des informations </p>


    <p>Il permet de réfléchir, faire émerger des idées, organiser ses idées/pensées, mais également d’expliquer ou valoriser des idées auprès des autres.</p>

    <p>«Le schéma heuristique [Mind Map] est une manifestation de la pensée irradiante et par conséquent une fonction naturelle de l'esprit. C'est une technique graphique efficace qui fournit un moyen universel de libérer le potentiel du cerveau.» (Buzan, 1995)</p>

    <p>«La méthode heuristique [Mind Mapping] peut s'appliquer à tous les aspects de la vie où un apprentissage plus efficace et une réflexion plus claire peuvent améliorer les performances humaines.» (Buzan, 1995)</p>

    <p>Règles du Mind map par Tony Buzan :</p>

    <img src="www/img/mind_mapping.png"

</section>