<section class="container motivation">
    <h2 id="motivation"><span>Motivation</span></h2>

    <img src="www/img/motivation1" alt="Motivation" class="imageinfo right">
    <p>La motivation est un  état dynamique qui permet de faire des choix, de s’y engager et de persévérer. C’est l’un des principaux moteurs dans le processus d’apprentissage. Tous les individus sont naturellement motivés d’apprendre. Mais des éléments extérieurs et intérieurs qui déterminent notre état d’esprit peuvent freiner ou activer cette disposition naturelle. Nos pensées négatives ou positives influencent nos sentiments et nos comportements. La démotivation provient de pensées négatives. <span>Nos pensées positives au contraire créent la motivation à s’engager dans quelque chose.</span> C’est au travers des situations quotidiennes et des situations d’apprentissages <span>réussies</span> que l’on tentera de trouver les ingrédients nécessaires à la motivation scolaire. </p>
    <img src="www/img/motivation2" alt="Motivation" class="imageinfo">
</section>