<section class="container organisation">
    <h2 id="organisation"><span>Organisation</span></h2>

    <p>Organiser signifie arranger des éléments pour en assurer le bon fonctionnement. S’organiser cela s’apprend, mais cela nécessite avant tout une volonté de changement, beaucoup de discipline au début pour acquérir ensuite des automatismes de travail.</p>
    <p>S’organiser permet de :</p>


    <p> -  mieux s’y retrouver </p>
    <p> -  mieux suivre et comprendre le fil conducteur d’une matière </p>
    <p> -  mieux réaliser les devoirs et exercices </p>
    <p> -  mieux étudier et s’y encourager </p>
    <p> -  <span>gagner du temps !</span></p>

    <img src="www/img/organisation.jpg" alt="Organisation" class="imageinfo">
</section>