<main class="container tarifs">
    <h2 class="title">Tarifs</h2>
	<p>Une séance de coaching individuelle dure entre une heure et une heure trente. Le tarif est de 50€ TTC la séance. </p>
	<p>Le règlement se fait en espèce à la fin de chaque séance. Les consultations non décommandées 48 heures à l'avance sont facturées.</p>
	<h3 class="orange">Que se passe-t-il si je ne peux me présenter à une séance?</h3>
	<p>Si vous avez un empêchement quelconque et que vous ne pouvez assurer le rdv, merci de l'annuler au plus tard 48 heures à l'avance. Toute consultation non décommandée dans ce délai vous sera facturée.</p>
	<p>Nous réservons en effet une heure de temps pour chaque rendez-vous. Nous avons besoin de savoir à l'avance comment nous organiser et pouvoir proposer les créneaux horaires qui se libèrent aux personnes qui en ont besoin. Il est donc essentiel, pour maintenir la qualité du service que nous proposons, que vous nous préveniez de vos absences suffisamment à l'avance. </p>
	<h3 class="orange">Des questions, des doutes, des précisions, une hésitation?</h3>
	<p>SI vous désirez obtenir de plus amples informations ou si vous avez des questions, n'hésitez pas à nous contacter. Vous pouvez nous contacter directement au 0466/94.60.94, par mail à l'adresse <a href="mailto:juliepetitlogo@gmail.com">juliepetitlogo@gmail.com </a>ou via le formulaire de contact.</p>
</main>
